Feat: Adding html files for error-messages
GalsenDev221/galsen.ui pull request #63
Opened 2024-11-05 13:17 UTC by bmaxtar

2024-11-05 23:37 UTC, NDOY3M4N requested changes
Je pense qu'il serait plus juducieux d'appeler ce component **Alert message**. Et on pourrait avoir plusieurs variations du même components comme le fait Bootstrap

2024-11-05 23:37 UTC, NDOY3M4N commented on src/data/components/galsen-ui-error-message.mdx
Il y a un bug au niveau du chargement. Je suggère de renommer ce fichier => `galsen-ui-error-messages.mdx` (au pluriel) car tu as placé tes composants HTML au niveau du dossier `public/components/error-messages`. La nommenclature doit rester la même.

2024-11-05 23:41 UTC, bmaxtar commented
Hum je vois l'idée, je ferai la modif inshalla 👍🏼

2024-12-27 01:01 UTC, daoodaba975 commented
Pour cette PR, il serai mieux de reprendre la logique du gestion des erreurs.

Les modifications que j'ai fait sur ce PR #77 ont ajoutés une gestion des erreurs (affichage de messages d'erreur détaillés lorsqu'un fichier est manquant ou ne peut pas être lu).

2024-12-27 01:01 UTC, closed without merging